name: Build App

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    build-and-test:
        strategy:
            matrix:
                nodejs-version: [18, 19, 20]
                # os: [ubuntu-latest]
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v5

            - name: Install Node - ${{ matrix.nodejs-version }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.nodejs-version }}

            - name: Install dependencies
              run: npm install
            
            - name: Run-test-cases
              run: npm test

            - name: Rename test results artifact file
              run: mv test-results.xml test-results-${{ matrix.nodejs-version }}.xml

            - name: Upload Test results
              uses: actions/upload-artifact@v4
              with:
                name: Test-Results-${{ matrix.nodejs-version }}
                path: test-results-${{ matrix.nodejs-version }}.xml