name: Build App

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v5

            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install
            
            - name: Run test cases
              run: npm test

            - name: Upload Test results
              uses: actions/upload-artifact@v4
              with:
                name: Test-Results
                path: test-results.xml