name: test-workflo-getdbcreds

on: 
    push:
        branches:
            - main
            - feature
permissions:
    id-token: write
    contents: read

jobs:
    login-aws:
        runs-on: ubuntu-latest
        steps:
            - name: login aws
              uses: aws-actions/configure-aws-credentials@v5.1.0
              with:
                aws-region: us-east-1
                role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
            - name: Get S3 details
              run: |
                aws version
                aws s3 ls
