name: solar-system

on:
    workflow_dispatch: 
    push:
        branches:
            main
env:
    MONGO_URI: ${{ vars.MONGO_URL }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        strategy:
            matrix:
                nodejs-version: [18]
                operating-system: [macos-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Download Node version
            uses: actions/setup-node@v6
            with:
                node-version: ${{ matrix.nodejs-version }}
        -   name: Install Dependencies
            run: npm install
        -   name: Run Test cases test
            run: |
                echo ${{ env.MONGO_URI }}
                npm test
        # -   name: Upload test results
        #     uses: actions/upload-artifact@v4
        #     with:
        #         name: Test-Results-${{matrix.nodejs-version}}-${{matrix.operating-system}}
        #         path: test-results.xml
    # post-unit-testing:
    #     strategy:
    #         matrix:
    #             nodejs-version: [18,19,20]
    #             operating-system: [ubuntu-latest, macos-latest]
    #     runs-on: ${{matrix.operating-system}}
    #     needs: unit-testing
    #     steps:
    #     -   name: Download artifacts
    #         uses: actions/download-artifact@v4
    #         with:
    #             name: Test-Results-${{matrix.nodejs-version}}-${{matrix.operating-system}}
    #     -   name: Read artifacts
    #         run: cat test-results.xml | head -n 10
    code-coverage:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18
        -   name: Install dependencies
            run: npm install
        -   name: Run Coverage
            continue-on-error: true
            run: npm run coverage
        -   name: Upload artifacts
            if: failure()
            uses: actions/upload-artifact@v4
            with:
                name: code-coverage-artifacts
                path: coverage
