name: solar-system

on:
    workflow_dispatch: 
    push:
        branches:
            main
env:
    MONGO_URI: ${{ vars.MONGO_URL }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        strategy:
            matrix:
                nodejs-version: [18]
                operating-system: [ubuntu-latest]
        runs-on: ${{ matrix.operating-system }}
        concurrency:
            group: solar-system-testing
            cancel-in-progress: true
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Download Node version
            uses: actions/setup-node@v6
            with:
                node-version: ${{ matrix.nodejs-version }}
        -   name: Cache Dependencies
            uses: actions/cache@v5
            with:
                path: node_modules
                key: ${{ matrix.operating-system }}-${{ matrix.nodejs-version }}-${{hashFiles('package-lock.json')}}
        -   name: Install Dependencies
            run: npm install
        -   name: Run Test cases test
            run: |
                echo ${{ env.MONGO_URI }}
                npm test
        # -   name: Upload test results
        #     uses: actions/upload-artifact@v4
        #     with:
        #         name: Test-Results-${{matrix.nodejs-version}}-${{matrix.operating-system}}
        #         path: test-results.xml
    # post-unit-testing:
    #     strategy:
    #         matrix:
    #             nodejs-version: [18,19,20]
    #             operating-system: [ubuntu-latest, macos-latest]
    #     runs-on: ${{matrix.operating-system}}
    #     needs: unit-testing
    #     steps:
    #     -   name: Download artifacts
    #         uses: actions/download-artifact@v4
    #         with:
    #             name: Test-Results-${{matrix.nodejs-version}}-${{matrix.operating-system}}
    #     -   name: Read artifacts
    #         run: cat test-results.xml | head -n 10
    code-coverage:
        strategy:
            matrix:
                nodejs-version: [18]
                operating-system: [ubuntu-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18
        -   name: Cache Dependencies
            uses: actions/cache@v5
            with:
                path: node_modules
                key: ${{ matrix.operating-system }}-${{ matrix.nodejs-version }}-${{hashFiles('package-lock.json')}}

        -   name: Install dependencies
            run: npm install
        -   name: Run Coverage
            continue-on-error: true
            run: npm run coverage
        -   name: Upload artifacts
            if: always()
            uses: actions/upload-artifact@v4
            with:
                name: ${{ matrix.operating-system }}-${{ matrix.nodejs-version }}-code-coverage-artifacts
                path: coverage
    docker-image-creation:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Code
            uses: actions/checkout@v4
        -   name: Login to docker
            uses: docker/login-action@v3
            with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
        -   name: Build and push image
            uses: docker/build-push-action@v6
            with:
                context: .
                push: true
                tags: nooli/solar-system:latest
        -   name: Pull image
            run: docker pull nooli/solar-system:latest
        -   name: List images
            run: docker images
            
